/*
 * Enum_Group_Function_Value.h
 *
 *  Created on: 15 juli 2021
 *      Author: Daniel Mårtensson
 */

#ifndef SAE_J1939_ENUMS_SAE_J1939_ENUM_GROUP_FUNCTION_VALUE_H_
#define SAE_J1939_ENUMS_SAE_J1939_ENUM_GROUP_FUNCTION_VALUE_H_

/* Enums for the acknowledgements */
typedef enum {
	GROUP_FUNCTION_VALUE_NORMAL = 0x0U,
	GROUP_FUNCTION_VALUE_CANNOT_MAINTAIN_ANOTHER_CONNECTION = 0x1U,
	GROUP_FUNCTION_VALUE_LACKING_NECESSARY_RESOURCES = 0x2U,
	GROUP_FUNCTION_VALUE_ABORT_TIME_OUT = 0x3U,
	GROUP_FUNCTION_VALUE_NO_CAUSE = 0xFFU
} ENUM_GROUP_FUNCTION_VALUE_CODES;

#endif /* SAE_J1939_ENUMS_SAE_J1939_ENUM_GROUP_FUNCTION_VALUE_H_ */
