/*
 * Enum_NAME.h
 *
 *  Created on: 15 juli 2021
 *      Author: Daniel Mårtensson
 */

#ifndef SAE_J1939_ENUMS_SAE_J1939_ENUM_NAME_H_
#define SAE_J1939_ENUMS_SAE_J1939_ENUM_NAME_H_

/* NAME fields enums */
typedef enum {
	/* Manufacturer code */
	MANUFACTURER_CODE_SONCEBOZ = 0x147U,
	MANUFACTURER_CODE_GRAYHILL = 0x126U,
	/* Industry group */
	INDUSTRY_GROUP_GLOBAL = 0x0U,
	INDUSTRY_GROUP_ON_HIGHWAY = 0x1U,
	INDUSTRY_GROUP_AGRICULTURAL_AND_FORESTRY = 0x2U,
	INDUSTRY_GROUP_CONSTRUCTION = 0x3U,
	INDUSTRY_GROUP_MARINE = 0x4U,
	INDUSTRY_GROUP_INDUSTRIAL_CONTROL_PROCESS = 0x5U,
	INDUSTRY_GROUP_RESERVED_6 = 0x6U,
	INDUSTRY_GROUP_RESERVED_7 = 0x7U,
	/* Function */
	FUNCTION_AUXILIARY_VALVES_CONTROL= 0x81U,
	FUNCTION_VDC_MODULE = 0x87U,
	/* Select of of them if you want the ECU to take own decision to change its own ECU address */
	ARBITRARY_ADDRESS_CAPABLE_NOT_CAPABLE = 0x0U,
	ARBITRARY_ADDRESS_CAPABLE_CAPABLE = 0x1U
	/* Add more here */
}ENUM_NAME_CODES;

#endif /* SAE_J1939_ENUMS_SAE_J1939_ENUM_NAME_H_ */
